### ISSUE TITLE
ファイル名の入力について

### ISSUE THREAD

**Issue by ys-practice** [HTanigawa-10/hrn-kadai#10]
https://github.com/HTanigawa-10/hrn-kadai/blob/68e976baebf463003726269810800a77cb0aed83/Purchase.java#L18

指摘ではなく興味本位ですが、
これってファイルのフルパスを引数に指定した場合は階層をあらわす"¥"などはエスケープされた状態で動きますか？

**Comment by HTanigawa-10** [comment]
eclipse上からしか実行できていませんが、フルパスでもエスケープされた状態で問題なく動くことを確認しています。
