### ISSUE TITLE
出力情報の扱いについて

### ISSUE THREAD

**Issue by ys-practice** [HTanigawa-10/hrn-kadai#11]
https://github.com/HTanigawa-10/hrn-kadai/blob/68e976baebf463003726269810800a77cb0aed83/Purchase.java#L20-L24

今回の仕様からすると商品ごとの合計金額のマップは不要な気がします。
Mapの仕様もあってか＜商品ID、商品名＞、＜商品ID、個数＞を別々に格納⇒出力時に合体させていますが、
この方法のデメリットとして、3つのMap操作のどれかで処理が正常に行かなかった場合など、
Map同士の不整合が起きる可能性を考慮する必要が出てきそうです。
また、今回の場合は商品名、個数を別々に使いたい、という条件はありません。
例えば、＜商品ID、（商品名、個数を保持するオブジェクト）＞のMapに一本化し、
このMapのキーセットで出力を行うのはいかがでしょうか。

**Comment by HTanigawa-10** [comment]
ご指摘頂きありがとうございます。
ご指摘頂きましたた通りに、Mapは一つにしたほうが良いと思いました。
合計金額のMapは、商品ごとの合計金額は分かったほうが良いだろうという自己判断で作ってしまっていたので、無駄な処理・工数をかけないよう気を付けたいと思います。
