### ISSUE TITLE
ExecutorServiceについて

### ISSUE THREAD

**Issue by ys-practice** [HTanigawa-10/hrn-kadai#13]
https://github.com/HTanigawa-10/hrn-kadai/blob/95d0ee9d42ad2ddc58f22e246eac0fd09a8dac81/ParallelProcessMain.java#L31

ちょっと要件と異なる部分があります。
要件を整理すると、各処理対象のサブ処理①～③を並列化することで実行時間の短縮を行う、ということです。
ParallelProcessSub1～3のreturn部分を以下のように書き換えると
どのスレッドで動いているかを見ることができます。
return this.procName + "-" + this.result + " : " + Thread.currentThread().getId();

処理対象1実行済み
処理対象2実行済み
処理対象3実行済み
処理対象4実行済み
処理対象5実行済み
処理対象1-サブ処理① : 10
処理対象1-サブ処理② : 10
処理対象1-サブ処理③ : 10
処理対象2-サブ処理① : 11
処理対象2-サブ処理② : 11
処理対象2-サブ処理③ : 11
処理対象3-サブ処理① : 12
処理対象3-サブ処理② : 12
処理対象3-サブ処理③ : 12
…

一番右に出ているのがスレッドIDですが、
一回のループごとにnewSingleThreadExecutorで単一スレッドを払い出しているため、
現状は各処理対象に対してサブ処理①～③は同じスレッドで動いていることになります。
要件を満たすためにはサブ処理①～③の3つの処理に別々のスレッドが割り当たるようにする必要があります。
newFixedThreadPoolかnewCachedThreadPoolを使ってみましょう。

**Comment by HTanigawa-10** [comment]
https://github.com/HTanigawa-10/hrn-kadai/blob/6f1f1d52c8106ee381fc548beae3a42dd3c3744f/ParallelProcessMain.java#L25-L26
サブ処理①～③の3つの処理に別々のスレッドが割り当てられるよう、newSingleThreadExecutorから
newFixedThreadPool(3)に修正しました。
※newCachedThreadPoolを使用した場合、4つ以上のスレッド・プールが作成されてしまう可能性があるため、「変更内容イメージ.xlsx」と異なってしまうと考えました。

**Comment by ys-practice** [comment]
修正内容確認しました。こちらで問題ありません、OKです！
